### ISSUE TITLE
Style cannot be edit in Mapbox Studio

### ISSUE THREAD

**Issue by mnboos** [openmaptiles/osm-bright-gl-style#11]
When trying to edit / view this style in Mapbox Studio (https://www.mapbox.com/studio/styles/) there appears an error:

![image](https://user-images.githubusercontent.com/22575883/33282798-0db297fa-d3aa-11e7-9ce2-7ae5aa0a2cfa.png)

**Comment by klokan** [comment]
Mapbox hosting supports only styles with all sources hosted on mapbox itself.

Our default style.json has source loading over http.

The workaround is to upload a sample OpenMapTiles MBTiles into Mapbox and replace in the JSON style the link to source to load this sample from Mapbox hosting.

Everything is step-by-step described at: https://openmaptiles.org/docs/style/mapbox-studio/
