### ISSUE TITLE
Error: unknown pbf field type exception

### ISSUE THREAD

**Issue by samizdis** [openmaptiles/osm-bright-gl-style#14]
Line 54 of style.json:
```
"sprite": "https://openmaptiles.github.io/osm-bright-gl-style/sprite",
```
references https://openmaptiles.github.io/osm-bright-gl-style/sprite, which is returning 404 not found.

I suspect this is the cause of errors I'm getting along the lines of:
```
Error: unknown pbf field type exception                     
    at Error (native)                                        
   mbgl: { class: 'Style',                                     
   severity: 'ERROR',                                        
   text: 'Failed to load glyph range 65024-65279 for font stack Klokantech Noto Sans CJK Regular: unknown pbf field type exception' }
```
but that could be something else.

It looks like this is present for many other styles (e.g. https://github.com/openmaptiles/positron-gl-style/blob/master/style.json) but I'm only raising the issue here.

**Comment by petrsloup** [comment]
The sprite URL is valid -- it's a base url, not a final image -- various suffixes have to be appended (see https://www.mapbox.com/mapbox-gl-js/style-spec/#root-sprite). For example https://openmaptiles.github.io/osm-bright-gl-style/sprite.png.

The error message is unrelated. Where do you see this error, under what circumstances?

**Comment by samizdis** [comment]
Thanks, that clears that up.

We're getting that error when zooming in to certain styles (positron-gl-style, for example, but not klokantech-basic) at sufficiently-high zooms (around zoom 5 or 6):

```
GET /styles/positron-gl-style/5/21/14.png 200 2856 - 18.122 ms
< snip ERROR MESSAGE FROM ABOVE /snip>
GET /styles/positron-gl-style/6/40/33.png - - - - ms
GET /styles/positron-gl-style/5/22/18.png - - - - ms
```

This has started in the past 48 hours in unchanged containers, so I assumed it was a network issue (like a broken link).

**Comment by samizdis** [comment]
This was solved by hosting the sprite/fonts locally.
