### ISSUE TITLE
Invalid MapBox GL JS Schema

### ISSUE THREAD

**Issue by ivanjaros** [openmaptiles/osm-bright-gl-style#22]
Hi,
I was looking for a way to style tiles and I found MapBox GL spec that was supposed to replace the Carto, which is great since one can easily parse json, whereas custom "css" syntax would be a tough task.

So I am currently writing parser for this json according to schema and I chose this style as my base. And to my surprise I see a lot of things like:
```
"line-width": {
        "base": 1.2,
        "stops": [
          [10, 0.8],
          [20, 6]
        ]
      }
```

which is invalid, according to the schema. It should be uint and not this custom definition. 

or
```
"fill-color": {
        "base": 1,
        "stops": [
          [12, "hsla(30, 19%, 90%, 0.4)"],
          [16, "hsla(30, 19%, 90%, 0.2)"]
        ]
      }
```

which is invalid color definition.

So I wonder, since there are *many* cases of this, what is going on?

**Comment by MartinMikita** [comment]
This is called data-driven styling: https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions, https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-ramps-scales-curves, https://docs.mapbox.com/mapbox-gl-js/style-spec/#other-function
