### ISSUE TITLE
Can reconsiter to reformat the source of the style.json

### ISSUE THREAD

**Issue by frodrigo** [openmaptiles/osm-bright-gl-style#24]
The source of the style was reformatted to less readable format. I guess with Mapbox Studio.
Please can you consider back to the original format, the one used by maputnik?

https://github.com/openmaptiles/osm-bright-gl-style/commit/fc8e4bda88f281e694b68760a041420d4c8b5c99

**Comment by daliborjanak** [comment]
We can reformat it again. This was caused because I developing styles now in the Cloud which strips the new lines.. Could be better to unify that somehow

**Comment by pathmapper** [comment]
@klokan yes, exactly:

https://github.com/maputnik/editor/blob/3c93c41de1e1a38bba288c13a41afd1d213defbf/src/components/modals/ExportModal.jsx#L6

When you open and export https://github.com/openmaptiles/osm-bright-gl-style/blob/master/style.json with https://maputnik.github.io/editor/, it looks like this:

![image](https://user-images.githubusercontent.com/20856381/66584945-48246300-eb86-11e9-9ad8-bda9aa6ebeed.png)

**Comment by pathmapper** [comment]
@daliborjanak thanks for the info.

> Could be better to unify that somehow

From https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec#gl-style-format:

"Will format the given style JSON to use standard indentation and sorted object keys."
